[versions]

## For Android
minAndroidSdk = "28"
compileAndroidSdk = "35"
targetAndroidSdk = "35"

agp = "8.6.0"
kotlin = "2.2.0"
compose = "1.9.2"
compose-plugin = "1.9.0"
compose-backhandler = "1.9.0"
compose-material3 = "1.4.0"
compose-resources = "1.9.0"
androidx-activityCompose = "1.10.1"
kotlinx-collections-immutable = "0.3.8"
stately = "2.0.0"
ktor = "2.3.7"
multiplatform-settings = "1.2.0"
coroutines = "1.10.2"
kotlinx-datetime = "0.6.0"
encryptedsharedprefs = "1.0.0"
recaptcha = "18.5.1"
lifecycle = "2.9.4"
koin = "4.0.0"
navigation-compose = "2.9.0-beta05"
detekt = "1.23.3"
serialization = "1.9.0"
google-services = "4.4.2"
firebase-crashlytics = "3.0.3"
firebase-bom = "33.1.1"
biometric = "1.1.0"
confetti = "0.6.0"
splash-screen = "1.0.1"
coil = "3.3.0"
camerax = "1.4.2"
ml-kit-recognition = "16.0.1"
kizitonwose-calendar-version = "2.7.0"
exifinterface = "1.3.7"
visionCommon = "17.3.0"
playServicesMlkitBarcodeScanning = "18.3.1"
moko-resources = "0.25.0"
moko-graphics = "0.10.1"
chucker = "4.1.0"
turbine = "0.8.0"
kotlinx-coroutines-test = "1.9.0"
mockk = "1.14.2"
nsexception = "1.0.3"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-resources" }
compose-back-handler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "compose-backhandler" }
kizitonwose-calendar = { module = "com.kizitonwose.calendar:compose-multiplatform", version.ref = "kizitonwose-calendar-version" }

androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "encryptedsharedprefs" }
android-recaptcha = { module = "com.google.android.recaptcha:recaptcha", version.ref = "recaptcha" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splash-screen" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version.ref = "exifinterface" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

resources-test = { module = "dev.icerock.moko:resources-test", version.ref = "moko-resources" }
test-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }

ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

multiplatformsettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }
multiplatformsettings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatform-settings" }

stately-concurrency = { module = "co.touchlab:stately-concurrency", version.ref = "stately" }

confetti = { module = "io.github.vinceglb:confettikit", version.ref = "confetti" }

chucker-library = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-library-noop = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }

detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
ml-text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "ml-kit-recognition" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-compose-network = { module = "io.coil-kt.coil3:coil-network-ktor2", version.ref = "coil" }

moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
moko-graphics = { module = "dev.icerock.moko:graphics", version.ref = "moko-graphics" }
moko-resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "moko-resources" }

mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }

camera-base = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
vision-common = { group = "com.google.mlkit", name = "vision-common", version.ref = "visionCommon" }
play-services-mlkit-barcode-scanning = { group = "com.google.android.gms", name = "play-services-mlkit-barcode-scanning", version.ref = "playServicesMlkitBarcodeScanning" }

nsexception = {module = "com.rickclephas.kmp:nsexception-kt-core", version.ref = "nsexception"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-mp = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }